### ISSUE TITLE
Build instructions result in error

### ISSUE THREAD

**Issue by jonas-schievink** [hotg-ai/librunecoral#17] opened 2021-08-16 10:14 UTC
I'm getting the following error during `make` inside the Docker container:

```
ERROR: /home/jonas/.cache/bazel/_bazel_jonas/9c55534d4233b9cdc493d7c1499d7160/external/org_tensorflow/tensorflow/core/util/BUILD:367:24: Action external/org_tensorflow/tensorflow/core/util/version_info.cc failed: (Exit 1): process-wrapper failed: error executing command 
  (cd /home/jonas/.cache/bazel/_bazel_jonas/9c55534d4233b9cdc493d7c1499d7160/sandbox/processwrapper-sandbox/73/execroot/runecoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /home/jonas/.cache/bazel/_bazel_jonas/install/1a4a2fac02d50c77031d44c0d91b8920/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'bazel-out/k8-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/util/version_info.cc) process-wrapper failed: error executing command 
  (cd /home/jonas/.cache/bazel/_bazel_jonas/9c55534d4233b9cdc493d7c1499d7160/sandbox/processwrapper-sandbox/73/execroot/runecoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /home/jonas/.cache/bazel/_bazel_jonas/install/1a4a2fac02d50c77031d44c0d91b8920/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'bazel-out/k8-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/util/version_info.cc)
Traceback (most recent call last):
  File "bazel-out/k8-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source", line 388, in <module>
    Main()
  File "bazel-out/k8-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source", line 378, in Main
    os.execv(args[0], args)
OSError: [Errno 2] No such file or directory: '/bin/python3'
```

This file does indeed not exist, instead the Python interpreter is located at `/usr/bin/python3`. I don't see the incorrect path in this repository, so it seems that some external dependency or Bazel itself is expecting to find it there.

**Comment by Michael-F-Bryan** [comment] 2021-08-16 10:17
@saidinesh5 do I need to publish a new version of the Docker image?

**Comment by saidinesh5** [comment] 2021-08-16 10:19
@Michael-F-Bryan this is odd. we are using this same docker image in the CI now.. ( https://github.com/hotg-ai/librunecoral/blob/master/.github/workflows/build_artifacts.yml#L15 )  https://github.com/bazelbuild/rules_docker/issues/1105 ?

**Comment by saidinesh5** [comment] 2021-09-02 02:53
Closing this issue for now because we have even changed the github docker containers and were unable to reproduce the issue.

**Closed by saidinesh5** 2021-09-02 02:53 UTC
